version: '3'

services:
  php:
    image: php:7.2-apache
    security_opt:
      - seccomp:unconfined
    volumes:
      - /d/docker_home/composer-test/php.ini:/usr/local/etc/php/php.ini
      - /d/docker_home/composer-test/html:/var/www/html
    ports:
      - 8080:80
  composer:
    image: composer:1.9.0
    command: 'composer create-project slim/slim-skeleton slimtest'
    volumes:
      - /d/docker_home/app:/app
    links:
      - php
